Re-use order id for capture
killbill/killbill-orbital-plugin pull request #15
Opened 2018-05-17 21:51 UTC by daliwei

cc @pierre for review.

2018-05-18 11:04 UTC, pierre requested changes

2018-05-18 11:04 UTC, pierre commented on spec/orbital/remote/shared_examples_for_payment_flow.rb
> +      payment_response.second_payment_reference_id = initial_order_id
`.should ==` ?

2018-05-18 18:34 UTC, daliwei commented on spec/orbital/remote/shared_examples_for_payment_flow.rb
> +      payment_response.second_payment_reference_id = initial_order_id
@pierre fixed.

2018-05-21 15:06 UTC, merged

2018-05-21 15:15 UTC, pierre commented
v0.1.10 released.

2018-05-22 23:21 UTC, daliwei commented
Thank you @pierre