Upgrade API version and support network tokenized cc
killbill/killbill-orbital-plugin pull request #5
Opened 2017-01-25 20:46 UTC by daliwei

@pierre Please review. Thanks,

2017-01-26 17:56 UTC, pierre requested changes

2017-01-26 17:56 UTC, pierre commented on lib/orbital/ext/active_merchant/active_merchant.rb
> +          "Content-Type" => "application/PTI70",
It looks like that's the only change? If so, how about doing it in the `merge` below (see `commit`), since we already override some of them?

2017-01-26 17:56 UTC, pierre commented on lib/orbital/ext/active_merchant/active_merchant.rb
> +            if action == AUTH_ONLY or action == AUTH_AND_CAPTURE
Nit: I try to stay away from `or` since its low precedence can be confusing (non-issue here though).

2017-01-26 17:56 UTC, pierre commented on lib/orbital/ext/active_merchant/active_merchant.rb
> +      def add_addtional_network_tokenization(xml, payment_method)
Typo

2017-01-26 17:56 UTC, pierre commented on spec/orbital/remote/request_spec/tokenized_creditcard_payload_spec.rb
> +describe 'Payment request for network tokenized card' do
Since these are all fast (stubbed Orbital) tests, they should be in `spec/orbital`, not `spec/orbital/remote`.

2017-01-26 17:56 UTC, pierre commented on spec/orbital/remote/request_spec/cvv_indicator_spec.rb
> +describe Killbill::Orbital::PaymentPlugin do
Similar remark regarding directory.

2017-01-26 19:01 UTC, daliwei commented on lib/orbital/ext/active_merchant/active_merchant.rb
> +          "Content-Type" => "application/PTI70",
Done in 87b8606

2017-01-26 19:02 UTC, daliwei commented on lib/orbital/ext/active_merchant/active_merchant.rb
> +            if action == AUTH_ONLY or action == AUTH_AND_CAPTURE
Good point. Done in fb2a9a0

2017-01-26 19:02 UTC, daliwei commented on lib/orbital/ext/active_merchant/active_merchant.rb
> +      def add_addtional_network_tokenization(xml, payment_method)
Done in fb2a9a0

2017-01-26 19:02 UTC, daliwei commented on spec/orbital/remote/request_spec/tokenized_creditcard_payload_spec.rb
> +describe 'Payment request for network tokenized card' do
Done in b9737f1

2017-01-26 19:02 UTC, daliwei commented on spec/orbital/remote/request_spec/cvv_indicator_spec.rb
> +describe Killbill::Orbital::PaymentPlugin do
Done in b9737f1

2017-01-26 19:04 UTC, daliwei commented
@pierre Thanks for the review! Made a few changes to address the comments. Please take a look.

2017-01-26 20:57 UTC, pierre requested changes

2017-01-26 20:57 UTC, pierre commented on spec/orbital/request_spec/cvv_indicator_spec.rb
> +require 'spec_helper'
If you put them in a new subdirectory, the `Rakefile` needs to be updated or tests won't be run. Also, the expectation (e.g. for Travis) is that `rake` runs the fast tests.

2017-01-26 20:57 UTC, pierre commented on spec/orbital/request_spec/cvv_indicator_spec.rb
> +      @pm         = create_payment_method(::Killbill::Orbital::OrbitalPaymentMethod, nil, @call_context.tenant_id, @properties, {})
Do you need this in these tests? I believe this will call the gateway since the endpoint isn't stubbed at this point.

2017-01-26 22:20 UTC, daliwei commented on spec/orbital/request_spec/cvv_indicator_spec.rb
> +require 'spec_helper'
oh I didn't notice that. I've always used `rspec` to run all the tests. Removed the subdirectory in 05273d2

2017-01-26 22:20 UTC, daliwei commented on spec/orbital/request_spec/cvv_indicator_spec.rb
> +      @pm         = create_payment_method(::Killbill::Orbital::OrbitalPaymentMethod, nil, @call_context.tenant_id, @properties, {})
Correct! Made some changes in e0d63a0 to avoid the unnecessary gateway calls.

2017-01-27 10:56 UTC, merged

2017-01-27 10:56 UTC, pierre commented
Thanks!